# four node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: /Users/cniackz/diskoa
      containerPath: /diskoa
      propagation: HostToContainer
  - role: worker
  - role: worker
  - role: worker
  - role: worker
