apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    name: my-route
    namespace: default
  spec:
    host: my-route-default.apps-crc.testing
    port:
      targetPort: https-console
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: passthrough
    to:
      kind: Service
      name: cesar-console
      weight: 100
    wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
---
apiVersion: v1
data:
  config.env: ZXhwb3J0IE1JTklPX1NUT1JBR0VfQ0xBU1NfU1RBTkRBUkQ9IkVDOjAiCmV4cG9ydCBNSU5JT19CUk9XU0VSPSJvbiIKZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0iVTFDTDBIRVlMTlBRRFBTMCIKZXhwb3J0IE1JTklPX1JPT1RfUEFTU1dPUkQ9IkxPMlJERVJDMEROVEdJSFdSSUs1Rk5FVkZKUEtFTkg0Igo=
kind: Secret
metadata:
  labels:
    v1.min.io/tenant: cesar
  name: cesar-env-configuration
  namespace: default
type: Opaque
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: cesar
  namespace: default
scheduler:
  name: ""
spec:
  configuration:
    name: cesar-env-configuration
  credsSecret:
    name: cesar-secret
  exposeServices:
    console: true
    minio: true
  features:
    enableSFTP: false
  image: minio/minio:RELEASE.2023-09-07T02-05-02Z
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - cesar
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-0
          topologyKey: kubernetes.io/hostname
    name: pool-0
    runtimeClassName: ""
    servers: 1
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "5368709120"
        storageClassName: crc-csi-hostpath-provisioner
    volumesPerServer: 1
  requestAutoCert: true
  users:
  - name: cesar-user-0
