apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: operator-csr 
spec:
  groups:
  - system:serviceaccounts
  - system:serviceaccounts:minio-operator
  - system:authenticated
  - system:nodes
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ3pEQ0NBYlFDQVFBd1V6RVZNQk1HQTFVRUNnd01jM2x6ZEdWdE9tNXZaR1Z6TVFzd0NRWURWUVFHRXdKVgpVekV0TUNzR0ExVUVBd3drYzNsemRHVnRPbTV2WkdVNktpNXRhVzVwYnk1dmNHVnlZWFJ2Y2k1amIyNXpiMnhsCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbHgyZkVub3dMMFVGNmdRdDZxU0UKOUhmQlNCWGZzdmhjZGxXbWJHODlvYjk0R3ExUFFibVkyWVpGdWp5ZDJ4ZVl6WlNCeHUrbVhLRlhBTmlMeVRxRQpPZWdJanlYNmtLTGhRTzVTbm9EUmJUU1FxZ2tOZ2prQjZlMXE1UTQ0eklVSnZyVlBLdVY4TkxmN3lXV3MxWFFNCnYxK3dIRHZBUXJwelcyN1BmdjU4WXNlNDFxOVJPeXM2eUdpbGdBT1dKVW1scTFBZ1lmdkcxa0dCQzAzTFI0SUkKZjVxajZkTWxZaWRiQWt6UjN0cVB4dE5YOU51U0ZuNmduditWWENWTm90S3BlY05ha0JrSituNWRHQmdCL1BrVApUbGJQc2lzMjR4bDlqSmpDTXN2MjVwcmNlNXE0WkR2ZDBVNkVOYVZnK25KOXpNTUtHMUNxVFhaZ1Q4VEVMUWZRCkh3SURBUUFCb0RRd01nWUpLb1pJaHZjTkFRa09NU1V3SXpBaEJnTlZIUkVFR2pBWWdoWnRhVzVwYnk1dmNHVnkKWVhSdmNpNWpiMjV6YjJ4bE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXVUbkY2bk5Ma2htbFZoNzdIWHVxdQphbnVTR0NLYkJpMW5nNUx5Y2dLQXVIMzNNK0hxWDEyYWd5TmFtbUxiampEUWpqQVlqWVgzN05GZGQwRHNjazZYCldpdUhJbFEwQm9NQkYrVGgwTnhPcGpDRk5hM0hYNTNiY0dQd0ZoczV1UlRoMnB6aFUvQTdCOTkyYVFBTnlmeVIKVzAwZVZaTGgranNhUjFhMk9vYXQ3SndxbEFMTmZIMWFlbFhHNzBLMURjbE1kSkI4aFozL2tzTEFaZ0t4aXdvQgpJay9aaFY0ZGhJd1lBcmdHNGxVR3plTGV2eW0vS3VVWVk0cG5ZYXZDdG1aeFhmdFJXaVVjMUJ0SWk1OG9UaW5FCnl3OEVhbHc4OFBVS3lYQ1pta0hHaDQ2QU50YmNmZjhvVUs1MEcxQ0l5TTQzM2xFejFoNkx3RkRvWXlVbGR6bFoKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
  - server auth
  username: system:serviceaccount:minio-operator:minio-operator
